### ISSUE TITLE
Very high memory usage

### ISSUE THREAD

**Issue by wangdemon** [ebeaufay/threedtiles#10]
The computer's memory usage is high and rising.

The testing model file

[output.002.zip](https://github.com/ebeaufay/threedtiles/files/9906737/output.002.zip)
[output.003.zip](https://github.com/ebeaufay/threedtiles/files/9906739/output.003.zip)
[output.004.zip](https://github.com/ebeaufay/threedtiles/files/9906740/output.004.zip)
[output.005.zip](https://github.com/ebeaufay/threedtiles/files/9906741/output.005.zip)
[output.006.zip](https://github.com/ebeaufay/threedtiles/files/9906742/output.006.zip)
[output.007.zip](https://github.com/ebeaufay/threedtiles/files/9906744/output.007.zip)
[output.008.zip](https://github.com/ebeaufay/threedtiles/files/9906746/output.008.zip)
[output.001.zip](https://github.com/ebeaufay/threedtiles/files/9906747/output.001.zip)

download model files, and uzip
![2](https://user-images.githubusercontent.com/20681339/199158231-a0720f10-2d9e-4856-9539-d3ff02b04cf9.png)

![1](https://user-images.githubusercontent.com/20681339/199158254-c6fc171c-2de5-45be-a549-1d06749ec3e1.png)

https://user-images.githubusercontent.com/20681339/199158267-1f8b857a-aa8f-46fa-87b4-1f361c2d1f0a.mp4

**Comment by ebeaufay** [comment]
Hi @wangdemon ,

There are several possible causes, the first thing you can try is to lower the geometric error multiplier.

Then, you need to check if the 3DTiles structure is optimal for streaming. Individual tiles should be around 500Kb and best is to have a tree structure like a bi-tree or octree.

Can you show me the structure inside the LOD folders?

Furthermore, you set the TileLoader maxCachedItems at 1000. If your tiles are big, this may be too much. Try to set it at a low number (even 0) to see if that fixes the issue

**Comment by wangdemon** [comment]
Thank you very much, When I change the geometric error multiplier to 0.01, the memory is really much less. 

But the maxCachedItems value, It seems to have no effect on memory. 

Watch the video below:

https://user-images.githubusercontent.com/20681339/199867883-ea921e76-db46-45ad-b88c-db43a409a403.mp4

I think the memory is still a little large.

The model has been uploaded, you can also test it

**Comment by ebeaufay** [comment]
I'm unable to open the zips, they are corrupt on my side.

**Comment by wangdemon** [comment]
[LOD-0.zip](https://github.com/ebeaufay/threedtiles/files/9935951/LOD-0.zip)

[LOD-1.zip](https://github.com/ebeaufay/threedtiles/files/9935982/LOD-1.zip)

[LOD-2.zip](https://github.com/ebeaufay/threedtiles/files/9935994/LOD-2.zip)

[LOD-3.zip](https://github.com/ebeaufay/threedtiles/files/9935987/LOD-3.zip)

[LOD-4.zip](https://github.com/ebeaufay/threedtiles/files/9936004/LOD-4.zip)

[LOD-5.zip](https://github.com/ebeaufay/threedtiles/files/9936009/LOD-5.zip)

[tileset.zip](https://github.com/ebeaufay/threedtiles/files/9936010/tileset.zip)

I have uploaded the model file again

**Comment by ebeaufay** [comment]
So first I see your tiles don't have an optimal structure because level 0 is 30 mb and level 5 is 27 mb. This indicates that the simplification is not sufficient (mesh and/or texture)

You have the same amount of files in each LOD meaning you don't split the meshes in a bi-tree or octree between levels.

For memory, open the developer tools F12 and go to performance and memory tab. The way you check memory usage, you look at chrome memory management, not the page itself

**Comment by wangdemon** [comment]
OK, thank you very much for your help.
