### ISSUE TITLE
Wrong transformation?

### ISSUE THREAD

**Issue by laraduarte** [ebeaufay/threedtiles#13]
Hi,

I'm having issues rendering a model after exporting IFC file to 3dtiles. 
In the Cesium the tileset is correct. 

The issue seems to be when I export by type instead of by group but then I have no colours on the model.

What can I do to fix this?

Tileset
[tiles.zip](https://github.com/ebeaufay/threedtiles/files/10882279/tiles.zip)

Cesium
![image](https://user-images.githubusercontent.com/1926934/222725243-6e117c05-88e3-4ffb-b714-f86b1a66b1f8.png)

threedTiles (export by type)
![image](https://user-images.githubusercontent.com/1926934/222725312-02d0d24d-d0ba-405b-b8f8-746e72aa2da3.png)

threedTiles (export by group)
![image](https://user-images.githubusercontent.com/1926934/222728173-eb009c76-6b42-4367-bc79-8a39d536a32d.png)

**Comment by ebeaufay** [comment]
Hi Lara,

What application are you referring to when you say you export by group or
type?

Emeric

**Comment by ebeaufay** [comment]
I see.

Please understand I cannot give free consultancy for a product that
competes with mine.

Sincerely,

Emeric

**Comment by laraduarte** [comment]
Hello again,

Sure I'm not asking you to do it, just give awareness that models like the one I attached (zip file) do not load properly with your plugin :)

If this is something you want to investigate or not it's up to you :)

Lara
