### ISSUE TITLE
yarn dev does not work

### ISSUE THREAD

**Issue by 3DGISKing** [ebeaufay/threedtiles#18]
![image](https://github.com/ebeaufay/threedtiles/assets/26606704/b1819f2b-c108-472b-ba29-f98fca6d2ed4)

**Comment by ebeaufay** [comment]
@3DGISKing 
I may have fixed this in version 9.1.15. 
I was importing these threejs addons directly from their location in the threejs release folder which webpack handles fine but threejs re-exports them in another way. By fixing the imports, I suspect that it will work with yarn but I haven't tested it.
