### ISSUE TITLE
Refinement type ADD not supported?

### ISSUE THREAD

**Issue by StrandedKitty** [ebeaufay/threedtiles#20]
It seems like "REPLACE" refinement strategy is always used, no matter the tileset settings. I see that there's a [`refinement` field](https://github.com/ebeaufay/threedtiles/blob/af74b6f494e39afe462bb375808f0230b9091610/src/tileset/OGC3DTile.js#L101) in `OGC3DTile.js`, but it seems like it never gets read from?

I'm trying to render a tileset that uses "ADD" refinement strategy, and when rendering it tiles at low levels of detail get hidden when more detailed tiles get loaded, which is not the expected behavior.

**Comment by ebeaufay** [comment]
That's right. I was waiting for someone to request it.

Personally, My only motivation is point-cloud tiles where ADD can make more sense than REPLACE. What's your use-case?

Anyhow, I will look to add support.

**Comment by StrandedKitty** [comment]
We are using Cesium ion to generate 3D tiles from .kml files containing vector building data.
In the resulting tileset there are multiple LODs: coarser LODs contain larger buildings, and finer LODs contain smaller buildings.

**Comment by ebeaufay** [comment]
I see. 
Ok I'll implement it, should be quite straightforward

**Comment by ebeaufay** [comment]
Sorry for the long time without an update. I fixed this in version 9.2.0 ADD and REPLACE will now both work
