### ISSUE TITLE
Cesium Tiling 1.1 data

### ISSUE THREAD

**Issue by jayantpaliwal** [ebeaufay/threedtiles#22]
I have generated tiling data from cesium ion.
https://github.com/CesiumGS/3d-tiles/tree/draft-1.1/specification/ImplicitTiling
but the viewer is not rendering the data. the issue is unable to read file from subtree structure.
How to bind these placeholder values levels and x y z ?
```
{
  "asset": {
    "version": "1.1",
    "extras": {
      "ion": {
        "georeferenced": false,
        "movable": true
      }
    }
  },
  "schema": {
    "id": "cesium-tiling-pipeline",
    "classes": {
      "tile": {
        "properties": {
          "tightBoundingBox": {
            "name": "Tight Bounding Box",
            "type": "SCALAR",
            "componentType": "FLOAT64",
            "array": true,
            "count": 12,
            "semantic": "TILE_BOUNDING_BOX"
          }
        }
      }
    }
  },
  "geometricError": 21.495847061053393,
  "root": {
    "boundingVolume": {
      "box": [2.15731143951416, 10.192809104919434, 0.8775157928466797, 12.410633087158203, 0.0, 0.0, 0.0, 12.410633087158203, 0.0, 0.0, 0.0, 12.410633087158203]
    },
    "geometricError": 0.7218289051132697,
    "refine": "REPLACE",
    "content": {
      "uri": "tiles/{level}/{x}/{y}/{z}.glb"
    },
    "metadata": {
      "class": "tile",
      "properties": {
        "tightBoundingBox": [2.15731143951416, 8.006588459014893, -0.9987449645996094, 12.410633087158203, 0.0, 0.0, 0.0, 10.224412441253662, 0.0, 0.0, 0.0, 10.534372329711914]
      }
    },
    "implicitTiling": {
      "subdivisionScheme": "OCTREE",
      "subtreeLevels": 6,
      "availableLevels": 6,
      "subtrees": {
        "uri": "subtrees/{level}/{x}/{y}/{z}.subtree"
      }
    }
  }
}
```

**Comment by ebeaufay** [comment]
Yes I didn't add support for implicit tiling yet, you're the first to ask.

I will add it. Any chance you can share a small dataset for testing?

**Comment by jayantpaliwal** [comment]
@ebeaufay 
implicit tiling datasets.
https://firebasestorage.googleapis.com/v0/b/dive-testing-268508.appspot.com/o/grid.zip?alt=media&token=7520776b-cd5e-474f-a0cc-071a902ac371

https://firebasestorage.googleapis.com/v0/b/dive-testing-268508.appspot.com/o/Sample%20(1.1).zip?alt=media&token=ca577f13-5d1b-4648-82b5-2de4e5ca6589

**Comment by ebeaufay** [comment]
Alright I'm working on this but the Implicit tiling is definitely a big complication on the format. 

Rant :
They talk about performance improvements but browsers are so performant at decoding json the gains seem minimal compared to the increased complexity. This kind of spec is why the standard is going to stay tied to very specialized and expensive software and OGC keeps wondering why their standards aren't more popular.  

Anyhow, thanks for the sample datasets. I'll update this thread when I have something working

**Comment by jayantpaliwal** [comment]
Hi @ebeaufay  any updates?

**Comment by ebeaufay** [comment]
Well I got a second request so it's definitely happening. It's planned for February.

**Comment by ebeaufay** [comment]
support for OGC3DTiles added in v9.2.15. 

Support includes gltf tiles, multiple contents and implicit tiling but not tile metadata. metadata can still be stored in the glb meshes.

On a side note, the stated advantages of 1.1 implicit tiling are:

- performance
- 1 on 1 mapping with other formats that have implicit tiling (cbd,... ) 
- easy to replace tiles.
