### ISSUE TITLE
Method to chech tile is ready seems not working properly with Google 3D tiles

### ISSUE THREAD

**Issue by hsonguk** [ebeaufay/threedtiles#23]
Thanks for the great work.  @ebeaufay 

I find tiles cannot load correctly in some area with Google 3D tiles.

For example, using your Ultra Globe example, if I move to Eifel Tower in France.

It seems down to when checking child tiles isReady, it hit the case that the Tile does not have children, no meshcontent and material visibility is False. Thus cannot hide the parent tile. Can you shed some light about your inference? 

Many thanks. 

![Snipaste_2024-02-27_09-24-51](https://github.com/ebeaufay/threedtiles/assets/65313968/9136ade8-fa19-4498-a773-98574556a8e4)

**Comment by ebeaufay** [comment]
Yep, I broke something recently, working on a fix right now

**Comment by ebeaufay** [comment]
it seems like google made some changes and have empty tiles that this code considers as an unloaded tile but it should be an easy fix

**Comment by ebeaufay** [comment]
Fixed in 9.2.8

**Comment by ebeaufay** [comment]
was a bit quick.. better fix in 9.2.9

**Comment by ebeaufay** [comment]
yeah I always forget the key but I change regenerate it no worries.

I may have made a mistake in the fix, try 9.2.12, should be better
