### ISSUE TITLE
Incompatibility with vite and corresponding fixes

### ISSUE THREAD

**Issue by mchao123** [ebeaufay/threedtiles#28]
![image](https://github.com/user-attachments/assets/11fa0bb6-0db5-43eb-af5f-26e7bf4ef5be)
![image](https://github.com/user-attachments/assets/b0205c3b-0cf5-4472-9864-02ba5930bcc3)
Using `new URL(url,window.location.origin)` instead of `new URL(url)` fixes this issue.

**Comment by ebeaufay** [comment]
this project : https://drive.google.com/file/d/1C102qriCsnra9EUbb8WzO4jZStp-eEah/view?usp=sharing
uses Vite as well as RTF, should be a good example for the configs
