### ISSUE TITLE
no local draco decoder found in draco-decoders

### ISSUE THREAD

**Issue by 3DGISKing** [ebeaufay/threedtiles#29]
![image](https://github.com/user-attachments/assets/47c5fa5f-3b03-465d-92e2-996e20837d52)

**Comment by 3DGISKing** [comment]
version 9.1.2

**Comment by ebeaufay** [comment]
That's  a warning. The library looks for local draco and ktx .wasm but if they're not packaged, they're fetched online.

The warning about duplicate KTX seems to indicate you already have a ktx loader?

You can specify your own KTXLoader and DracoLoader though you might have to update the versuon, I'll update the readme but it's documented in the jsdocs: https://www.jdultra.com/threedtiles/docs/

**Comment by 3DGISKing** [comment]
we do not want to use the local version.
it looks like that https://www.gstatic.com/draco/versioned/decoders/1.4.3/ is not valid url.

**Comment by ebeaufay** [comment]
Indeed, alright I'll fix it and document how to specify your own KTXLoader and DracoLoader

**Comment by ebeaufay** [comment]
Hi, I updated the readme in section "Meshopt, Draco and Ktx2"

However you'll have to move to the latest version of the lib.
