### ISSUE TITLE
The project is for bowser or Nodejs?

### ISSUE THREAD

**Issue by easyfrog** [ebeaufay/threedtiles#5]
I go an error:
<img width="388" alt="image" src="https://user-images.githubusercontent.com/10724325/173013087-0a59a0b3-b7b8-4a5f-a3bd-d2d01c7bb999.png">

I see the code like  `require('path')` in source. So is this project only for nodejs?
<img width="523" alt="image" src="https://user-images.githubusercontent.com/10724325/173012883-1f6dbd24-def8-4cdc-bef1-04f63f66fa15.png">

**Comment by ebeaufay** [comment]
Project is definitely for web browser but I guess require isn't available by default on browsers indeed. I use webpack which I guess automatically converts it. 

I'll check if I can convert the require to an import

**Comment by ebeaufay** [comment]
So webpack includes Path-Browserify by default that should make the path lib accessible.
You can add it yourself from npm https://github.com/browserify/path-browserify

**Comment by ebeaufay** [comment]
Ok I fixed it by replacing **const path = require('path')** with **import * as path from "path-browserify"**
