### ISSUE TITLE
how to create tileset.json? --help

### ISSUE THREAD

**Issue by MeRahulAhire** [ebeaufay/threedtiles#9]
I'm new to 3d tiles and want to know that how can I make `tileset.json`out of my glb model?

**Comment by ebeaufay** [comment]
Hi Rahul,

I have a tool to create the tileset but I don't share it for free.
If you can, send me the model here (emericbeaufays@gmail.com) and I'll convert it for you.

Else I'm working on a web-service but that'll take some time until it's available

**Comment by MeRahulAhire** [comment]
That's so kind of you but I'd like to know that how can I create tileset.json? Any tool or blender Ad-on?

**Comment by ebeaufay** [comment]
I know only of paid tools including two that I developed. 

There is also one free tool from "bricsys" but you'll need to look for it. I believe it only came with c++ API and I'm not sure it handles textures.

You might find other tools that do a 1:1 conversion but be careful they do that without generating levels of detail, hence it's quite pointless to use 3DTiles for that.

The tool I propose handles any size dataset and produces optimal tiling and multileveling with texture. Then, you can really stream huge datasets over the web. 

The tool comes as a CLI, a java API and a web-service although the web-service currently requires data to be on an s3 bucket.
The normal input is OBJ but if you would be interested, I could add a glb/gltf decoder.
